# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Minify Css Js and Html files in GitHub Action
      uses: amireshoon/minifyAction@v1.1
    - name: Run Serenity Tests with Maven command
      run: mvn clean verify -Denvironment=demo
      continue-on-error: true
    - name: Upload Serenity Report
      uses: actions/upload-artifact@v3
      with:
        name: Serenity Report
        path: target/site/serenity
    - name: Minify Serenity Report
      uses: dorny/gh-action-html-minifier@v1
      with:
        html_file: target/site/serenity/index.html
        
    - uses: actions/upload-artifact@v3
      with:
        name: index.html
        path: target/site/serenity/index.html
    - name: HTML Preview
      id: html_preview
      uses: pavi2410/html-preview-action@v2
      with:
        html_file: 'index.html'
        name: index.html
        path: target/site/serenity/
    - name: Upload Serenity Report
      uses: actions/upload-artifact@v2
      with:
        name: Serenity Report
        path: target/site/serenity/index.html
